config/routes.rb
Rails.application.routes.draw do
  post "/rate", to: "rater#create", as: "rate"
  root "static_pages#home"

  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    member do
      get :following
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  namespace :admin do
    resources :restaurants, only: :index
    resources :users, except: :show
  end

  namespace :manager do
    resources :restaurants, except: :destroy do
      resources :categories
      resources :foods, only: [:new, :create, :edit, :update]
    end
    resources :orders, only: [:index, :update] do
      patch "/cancel_order", to: "orders#cancel_order"
    end
    get "/all_orders", to: "orders#all_orders"
    resources :notifications, only: [:index]
  end

  namespace :user do
    resources :orders, only: [:index, :update] do
      patch "/confirm_receive", to: "orders#confirm_receive"
    end
  end

  resources :restaurants do
    get "/restaurant_foods", to: "restaurants#restaurant_foods"
    resources :suggests
    member do
      get :followers
    end
  end

  resources :foods do
    post "/delete_food", to: "foods#update_status"
    resources :images
    resources :comments do
      get :reply
    end
  end

  resources :relationships, only: [:create, :destroy]

  get "/search", to: "search#index"
  get "/restaurants/:city", to: "restaurants#index"
  get "/foods/:category", to: "foods#index"
  resources :order_details
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  has_one :notification
  has_many :order_details, dependent: :destroy

  enum status: [:unordered, :ordered, :accepted, :cancel, :received]

  scope :find_order, ->(id){where user_id: id}
  scope :find_order_stt, ->(stt){where status: stt}
  scope :all_ordered_manager, ->(stt){where.not status: stt}
  scope :find_order_id, ->(id){where id: id}
end

app/controllers/manager/categories_controller.rb
class Manager::CategoriesController < ApplicationController
  before_action :logged_in_user, only: %i(create destroy)
  before_action :is_manager?
  before_action :load_restaurant
  before_action :load_categories

  def new
    @category = Category.new
    @image = @category.images.build
  end

  def create
    @category = @restaurant.categories.build category_params
    if @category.save
      flash[:success] = t "flashs.create_category_success"
      redirect_back_or @restaurant
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit :parent_id, :name,
      images_attributes: [:id, :image, :imageable_id, :imageable_type]
  end

  def load_restaurant
    @restaurant = Restaurant.find_by id: params[:restaurant_id]
    return if @restaurant
    flash[:danger] = t "flashs.not_found_restaurant"
    redirect_to root_path
  end

  def load_categories
    @categories = @restaurant.categories.all
  end
end

app/controllers/manager/foods_controller.rb
class Manager::FoodsController < ApplicationController
  before_action :logged_in_user, only: %i(create destroy)
  before_action :is_manager?
  before_action :load_restaurant
  before_action :load_categories
  before_action :load_food, only: [:update, :edit]
  before_action :load_images, only: :edit

  def index; end

  def new
    @food = Food.new
    Settings.image_times.times do
      @image = @food.images.build
    end
    store_location
  end

  def create
    @food = @restaurant.foods.build food_params
    if @food.save
      flash[:success] = t "food.message.create_success"
      redirect_to @food
    else
      render :new
    end
  end

  def edit; end

  def update
    if @food.update_attributes food_params
      flash[:success] = t "food.message.update_success"
      redirect_to @food
    else
      flash[:danger] = t "food.message.update_fail"
      render :edit
    end
  end

  def update_status
    @food = Food.find_by_id params[:food_id]
    if @food.update_attributes status: :disable
      flash[:success] = t "food.message.disable_success"
      redirect_to @food
    else
      flash[:danger] = t "food.message.disable_fail"
      redirect_to root_url
    end
  end

  private

  def food_params
    params.require(:food).permit :name, :description, :price, :rate,
      :category_id, :status,
      images_attributes: [:id, :image, :imageable_id, :imageable_type]
  end

  def load_restaurant
    @restaurant = Restaurant.find_by id: params[:restaurant_id]
  end

  def load_categories
    @categories = @restaurant.categories.all
  end

  def load_food
    @food = Food.find_by_id params[:id]
    return if @food
    flash[:danger] = t "food.message.not_found"
    redirect_to root_url
  end

  def load_images
    @images = @food.images
  end
end

app/controllers/manager/menus_controller.rb
class Manager::MenusController < ApplicationController
  before_action :find_restaurant, only: [:show]
  before_action :find_food, only: [:edit]

  def show
    @foods = Food.find_food_enable(params[:id]).page(params[:page]).per Settings.rows
  end

  def edit; end

  def delete_food
    @food = Food.find_by_id params[:menu_id]
    restaurant_id = @food.restaurant_id
    if @food.update_attributes status: :disable
      flash[:success] = t "food.message.disable_success"
      redirect_to manager_menu_path(restaurant_id)
    else
      flash[:danger] = t "food.message.disable_fail"
      redirect_to manager_menu_path(restaurant_id)
    end
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find_by_id params[:id]
    return if @restaurant.nil?
  end

  def find_food
    @food = Food.find_by_id params[:id]
    @categories = @food.restaurant.categories
    restaurant_id = @food.restaurant_id
    return if @food.nil?
  end
end

app/controllers/manager/notifications_controller.rb
class Manager::NotificationsController < ApplicationController
  def index
    @notifications = Notification.notification.page(params[:page]).per Settings.rows
  end
end

app/controllers/manager/orders_controller.rb
class Manager::OrdersController < ApplicationController
  before_action :is_manager?

  def index
    @orders = Order.find_order_stt(:ordered).page(params[:page]).per Settings.rows
  end

  def all_orders
    @orders = Order.all_ordered_manager(:unordered).page(params[:page]).per Settings.rows
  end

  def update
    @order = Order.find_by_id params[:id]
    @sum_total = OrderDetail.find_or_detail(params[:id]).sum(:total_price)
    return if @order.nil?
    if @order.update_attributes status: :accepted, total_pice: @sum_total
      flash[:success] = t "order.message.ordered_success"
      redirect_to manager_orders_url
    else
      flash[:danger] = t "order.message.ordered_failure"
      redirect_to manager_orders_url
    end
  end

  def cancel_order
    @order = Order.find_by_id params[:order_id]
    if @order.update_attributes status: :cancel
      flash[:success] = t "order.message.cancel_success"
      redirect_to manager_orders_url
    else
      flash[:danger] = t "order.message.cancel_failure"
      redirect_to manager_orders_url
    end
  end
end

app/controllers/manager/restaurants_controller.rb
class Manager::RestaurantsController < ApplicationController
  before_action :is_manager?
  before_action :find_restaurant, only: %i(show edit update destroy)

  def index
    @restaurants = Restaurant.includes(:user)
                             .where("restaurants.user_id = #{current_user.id}")
  end

  def new
    @restaurant = Restaurant.new
  end

  def show; end

  def create
    @restaurant = current_user.restaurants.build restaurant_params
    @restaurant.user_id = current_user.id
    if @restaurant.save
      flash[:success] = t "manager.create_success"
      redirect_to manager_restaurants_path
    else
      flash[:error] = t "manager.restaurants.create_error"
      render :new
    end
  end

  def edit; end

  def update
    if @restaurant.update_attributes restaurant_params
      flash[:success] = t "manager.restaurants.update_success"
      redirect_to manager_restaurants_path
    else
      render :edit
    end
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find_by id: params[:id]
    return if @restaurant
    flash[:danger] = t "admin.restaurants.not_found"
  end

  def restaurant_params
    params.require(:restaurant).permit :name, :description, :address,
      :phone_number, :user_id
  end
end

app/controllers/user/orders_controller.rb
class User::OrdersController < ApplicationController
  before_action :logged_in_user
  before_action :is_user?

  def index
    @orders = Order.find_order(current_user.id).page(params[:page]).per Settings.rows
  end

  def update
    @order = Order.find_by_id params[:id]
    @sum_total = OrderDetail.find_or_detail(params[:id]).sum(:total_price)
    return if @order.nil?
    if @order.update_attributes status: :ordered, total_pice: @sum_total
      content = t "notification.ordered_content"
      create_notification(params[:id], content)
      flash[:success] = t "order.message.ordered_success"
      redirect_to foods_url
    else
      flash[:danger] = t "order.message.ordered_failure"
      redirect_to order_details_url
    end
  end

  def confirm_receive
    @order = Order.find_by_id params[:order_id]
    if @order.update_attributes status: :received
      content = t "notification.received_content"
      update_notification(params[:order_id], content)
      flash[:success] = t "order.message.confirm_received_success"
      redirect_to user_orders_url
    else
      flash[:danger] = t "order.message.confirm_received_failure"
      redirect_to user_orders_url
    end
  end

  private

  def create_notification id, content
    OrderDetail.find_or_detail(id).each do |order_detail|
      @notification = Notification.new
      @notification.content = content
      @notification.restaurant_id = order_detail.restaurant_id
      @notification.order_id = params[:id]
      @notification.save
    end
  end

  def update_notification id, content
    OrderDetail.find_or_detail(id).each do |order_detail|
      restaurant_id = order_detail.restaurant_id
      @notification = Notification.find_by restaurant_id: restaurant_id
      @notification.update_attributes content: content
    end
  end
end

app/helpers/manager/restaurants_helper.rb
module Manager::RestaurantsHelper
  def get_most_ordered_foods restaurant
    most_ordered = {}
    restaurant.foods.each do |food|
      most_ordered[food.name] = 0
      food.order_details.each do |order_details|
        most_ordered[food.name] += order_details.quantity
      end
    end
    most_ordered.sort_by{|_key, value| value}.last(Settings.most_ordered_foods).to_h
  end

  def get_revenue_per_day restaurant
    OrderDetail.get_revenue restaurant
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def load_order id
    @order = Order.find_order_id id
  end
end

app/views/manager/orders/_detail.html.erb
<div class="row col-md-12" id="detail-submit" >
  <div class="row col-md-8">
    <div class="col-md-6">
      <p><strong>
        <%= t "order.label.sum_order"%>:&nbsp;
        <%= od_res.total_pice %>&nbsp;$
      </strong></p>
    </div>
  </div>
  <div class="row col-md-4 pull-right">
    <% if od_res.accepted? %>
      <p id="status"><i><%= t "order.status.confirmed" %></i></p>
    <% elsif od_res.received? %>
      <p id="status"><i><%= t "order.status.sended" %></i></p>
    <% elsif od_res.cancel? %>
      <p id="status"><i><%= t "order.status.cancel" %></i></p>
    <% else %>
      <p id="status"><i><%= t "order.status.not_confirmed" %></i></p>
    <% end %>
  </div>
</div>

app/views/manager/orders/_form_submit.html.erb
<div class="row col-md-12" id="detail-submit" >
  <div class="row col-md-8">
    <div class="col-md-6">
      <p><strong>
        <%= t "order.label.sum_order"%>:&nbsp;
        <%= od_res.total_pice %>&nbsp;$
      </strong></p>
    </div>
  </div>
  <div class="row col-md-4 pull-right">
    <div class="col-md-6">
      <%= link_to t("order.submit.accept_order"), manager_order_path(od_res.id),
        method: :patch, class:"btn btn-success"%>
    </div>
    <div class="col-md-6">
      <%= link_to t("order.submit.cancel_order"), manager_order_cancel_order_path(od_res.id), method: :patch, class:"btn btn-danger"%>
    </div>
  </div>
</div>

app/views/manager/orders/all_orders.html.erb
<h2>
  <%= t "order.submit.all_orders" %>
</h2>
<% if @orders.blank? %>
    <h1><%= t "order.message.no_order" %></h1>
<% else %>
  <% @orders.each do |od_res| %>
    <% if find_order_detail_o_id(od_res).count > 1 %>
      <% find_order_detail_o_id(od_res).each do |detail| %>
        <% next if check_order_restaurant(find_order_detail_o_id(od_res).first.restaurant_id, current_user.id).blank? %>
        <% if !check_order_restaurant(detail.restaurant_id, current_user.id).blank? %>
          <div class="row col-md-12" id="each-detail">
            <%= render "shared/detail_food", detail: detail %>
            <%= render "shared/detail_user", od_res: od_res %>
          </div>
        <% end %>
      <% end %>
      <%= render "manager/orders/detail", od_res: od_res %>
    <% else %>
      <% next if check_order_restaurant(find_order_detail_o_id(od_res.id).first.restaurant_id, current_user.id).blank? %>
      <% if !check_order_restaurant(find_order_detail_o_id(od_res.id).first.restaurant_id, current_user.id).blank? %>
        <div class="row col-md-12" id="each-detail">
          <%= render "shared/detail_food", detail: find_order_detail_o_id(od_res).first %>
          <%= render "shared/detail_user", od_res: od_res %>
        </div>
      <% end %>
      <%= render "manager/orders/detail", od_res: od_res %>
    <% end %>
  <% end %>
  <%= paginate @orders, theme: "twitter-bootstrap-3" %>
<% end %>

app/views/manager/orders/index.html.erb
<h2 class="text-center">
  <%= t "order.submit.orders_need_confirm" %>
  <%= link_to t("order.submit.all_orders"), manager_all_orders_path, class:"btn btn-primary pull-right" %>
</h2>
<% if @orders.blank? %>
  <h3><i><%= t "order.message.no_order" %></i></h3>
<% else %>
  <% @orders.each do |od_res| %>
    <% if find_order_detail_o_id(od_res).count > 1 %>
      <% find_order_detail_o_id(od_res).each do |detail| %>
        <% next if check_order_restaurant(find_order_detail_o_id(od_res).first.restaurant_id, current_user.id).blank? %>
        <% if !check_order_restaurant(detail.restaurant_id, current_user.id).blank? %>
          <div class="row col-md-12" id="each-detail">
            <%= render "shared/detail_food", detail: detail %>
            <%= render "shared/detail_user", od_res: od_res %>
          </div>
        <% end %>
      <% end %>
      <%= render "manager/orders/form_submit", od_res: od_res %>
    <% else %>
      <% next if check_order_restaurant(find_order_detail_o_id(od_res.id).first.restaurant_id, current_user.id).blank? %>
      <% if !check_order_restaurant(find_order_detail_o_id(od_res.id).first.restaurant_id, current_user.id).blank? %>
        <div class="row col-md-12" id="each-detail">
          <%= render "shared/detail_food", detail: find_order_detail_o_id(od_res).first %>
          <%= render "shared/detail_user", od_res: od_res %>
        </div>
      <% end %>
      <%= render "manager/orders/form_submit", od_res: od_res %>
    <% end %>
  <% end %>
  <%= paginate @orders, theme: "twitter-bootstrap-3" %>
<% end %>