config/routes.rb
Rails.application.routes.draw do
  post "/rate", to: "rater#create", as: "rate"
  root "static_pages#home"

  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    member do
      get :following
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  namespace :admin do
    resources :restaurants, only: :index
    resources :users, except: :show
  end

  namespace :manager do
    resources :restaurants, except: :destroy do
      resources :categories
      resources :foods, only: [:new, :create, :edit, :update]
    end
    resources :orders, only: [:index, :update] do
      patch "/cancel_order", to: "orders#cancel_order"
    end
    get "/all_orders", to: "orders#all_orders"
    resources :notifications, only: [:index]
  end

  namespace :user do
    resources :orders, only: [:index, :update] do
      patch "/confirm_receive", to: "orders#confirm_receive"
    end
  end

  resources :restaurants do
    get "/restaurant_foods", to: "restaurants#restaurant_foods"
    resources :suggests
    member do
      get :followers
    end
  end

  resources :foods do
    post "/delete_food", to: "foods#update_status"
    resources :images
    resources :comments do
      get :reply
    end
  end

  resources :relationships, only: [:create, :destroy]

  get "/search", to: "search#index"
  get "/restaurants/:city", to: "restaurants#index"
  get "/foods/:category", to: "foods#index"
  resources :order_details
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
  attr_accessor :user, :order_detail
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @categories = Category.all.map{|category| [category.name, category.id]}
    @restaurants = if logged_in? && is_manager?
                     Restaurant.where user_id: current_user.id
                   elsif logged_in? && is_user?
                     Restaurant.all
    end
  end

  def help; end

  def about; end

  def contact; end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<%= provide :title, t(".title") %>
<div class="row">
  <% if logged_in? && !is_admin? && !is_manager? %>
    <%= render "foods/filter_form" %>
  <% end %>
</div>
<% if logged_in? %>
  <% if is_manager? %>
    <div class="row row-flex">
      <% @restaurants.each do |r| %>
        <div class="col-md-12">
          <h2 class="block-title"><%= r.name %></h2>
          <h4 class="about-us">
            <i><%= t "restaurant.about_us" %>:</i>&nbsp;<%= r.description %></span>
          </h4>
        </div>
        <div class="col-md-12">
          <% find_food_restaurant(r.id).each do |f| %>
            <% if f.enable? %>
              <p>
                <i><strong><%= t "food.label.name" %>:</strong></i>&nbsp;
                <%= link_to f.name, food_path(f.id) %>
              </p>
              <div class="row">
                <% f.images.each do |i| %>
                  <div class="col-md-3">
                    <%= image_tag i.image.url, class: "img-food", crop: :fill %>
                  </div>
                <% end %>
              </div>
            <% end %>
          <br>
          <% end %>
        </div>
      <% end %>
    </div>
  <% elsif is_admin? %>

  <% else %>
    <% @restaurants.each do |r| %>
      <div class="col-md-6">
        <h3 class="block-title"><%= link_to r.name, r %></h3>
        <div class="about-us">
          <i><%= t "restaurant.about_us" %>:</i>
            <ul>
              <li><%= r.description %></li>
              <li><%= r.address %></li>
              <li><%= r.phone_number %></li>
            </ul>
        </div>
      </div>
    <% end %>
  <% end %>
<% else %>
  <div class="py-5 text-center welcome-home">
    <div class="container py-5">
      <div class="row">
        <div class="col-md-12">
          <h1 class="display-3 mb-4"><%= t ".welcome" %></h1>
          <p class="lead mb-5"><%= t ".welcome_text" %></p>
          <%= link_to t("layouts.header.signin"), signin_path, class: "btn btn-lg mx-1 btn-secondary" %>
          <%= link_to t("layouts.header.signup"), signup_path, class: "btn btn-lg btn-primary mx-1" %>
        </div>
      </div>
    </div>
  </div>
<% end %>